---
title: "9_1_PCA"
author: "Ji-Lung Hsieh"
output:
  html_notebook:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: united
    highlight: tango
---

```{r}
library(tidyverse)
library(lubridate)

```


# Loading data
```{r}
load("data/CitizensMiaoKou_short.rda")
```


## Summarizing data and bulding affiliation matrix

```{r}
reaction2015 %>% count(type)

high_user2015 <- reaction2015 %>%
	count(id, sort = TRUE) %>%
	filter(n >= 5)

like2pid2015 <-  reaction2015%>%
	count(id, pid) %>%
	filter(id %in% high_user2015$id) %>%
	spread(pid, n, fill=0)

dim(like2pid2015)
```


# filter high frequency users
```{r}
like_pid2015 <-  reaction2015 %>%
    group_by(id) %>%
    filter(n() >= 5) %>%
    ungroup() %>%
    select(id, pageid = pid)
```


# Working with bipartie/affiliation network data in R
* Soloman messing's page https://solomonmessing.wordpress.com/2012/09/30/working-with-bipartiteaffiliation-network-data-in-r/

```{r}
library(Matrix)

toAffMatrix <- function(like_pid){
	A <- spMatrix(nrow=length(unique(like_pid$id)),
				  ncol=length(unique(like_pid$pageid)),
				  i = as.numeric(factor(like_pid$id)),
				  j = as.numeric(factor(like_pid$pageid)),
				  x = rep(1, length(as.numeric(like_pid$id))) )
	row.names(A) <- levels(factor(like_pid$id))
	colnames(A) <- levels(factor(like_pid$pageid))
	Acol <- tcrossprod(t(A))
	Matrix(Acol)	
}

m2015 <- toAffMatrix(like_pid2015)
```

```{r}
m2015_1 <- m2015/apply(m2015, 1, max)
m2015.pca <- prcomp(m2015_1,
                 center = TRUE,
                 scale. = TRUE)

plot(m2015.pca, type = "l")
```



```{r}
m2015.pca$x %>%
  as.data.frame() %>%
  ggplot(aes(PC1)) + geom_density()


m2015.pca$x %>%
  as.data.frame() %>%
  ggplot(aes(PC2)) + geom_histogram()

m2015.pca$x %>%
  as.data.frame() %>%
  ggplot(aes(PC2)) + geom_density()

m2015.pca$x %>% # data projected in pca space
  as.data.frame() %>%
  ggplot(aes(PC1, PC2)) + geom_jitter()

m2015.pca$x %>%
  as.data.frame() %>%
  ggplot(aes(PC1, PC2)) + geom_density2d()

```

## explore
```{r}
df2015.pca <- m2015.pca$x %>%
	as.data.frame %>%
	select(PC1, PC2) %>%
	mutate(id=rownames(.)) %>%
	left_join(post2015) %>%
	arrange(desc(PC2)) %>%
	mutate(hour=hour(created_time)) %>%
	mutate(week=week(created_time))

plot(df2015.pca[,c(1, 2, 13:17)])
```

```{r}
df2015.pca %>%
	ggplot(aes(PC1, PC2)) + 
	geom_point(alpha = 0.5)

```



```{r}

df2015.pca %>%
	ggplot(aes(PC1, PC2, color=factor(type))) + 
	geom_point(alpha = 0.5)

df2015.pca %>%
	ggplot(aes(PC1, PC2, color=week)) +
	geom_point()
```





## convert to user scale
```{r}
m2015.pca$x
like2pid.m <- as.matrix(like2pid2015[,-1])
PC2.v <- as.data.frame(m2015.pca$x)$PC2

test <- t(t(like2pid.m)*PC2.v)
test.freq <- apply(test, 1, mean)
plot(density(test.freq))
```


## network visualization
```{r}
library(igraph)
dim(as.matrix(m2015))
g2 <- graph.adjacency(as.matrix(m2015),mode="undirected",weighted=TRUE)
	# graph_from_adjacency_matrix(m2015, weighted=TRUE, mode = "undirected")
hist(E(g2)$weight, n=1000, xlim = c(1, 100))

g2s <- simplify(g2, remove.multiple = T, remove.loops = T, edge.attr.comb=c(weight="sum", type="ignore") )
ecount(g2s)
test <- which(E(g2s)$weight > 10)
g2s.copy <- delete.edges(g2s, which(E(g2s)$weight < 10))
ecount(g2s.copy)
plot(g2s.copy, 
	 vertex.label=NA, 
	 vertex.size=1,
	 edge.curved=0.2,
	 layout=layout_with_kk)

```

## MDS
```{r}
d <- dist(m2015)
fit <- cmdscale(d,eig=TRUE, k=2)
x <- fit$points[,1]
y <- fit$points[,2]
plot(x, y)
```



