---
title: "期中報告"
author: "劉德翎 羅健華"
output: 
  html_document:
    toc: TRUE
---
# 1. Data

## 1.1. Environment setup
```{r, message=FALSE}
#install.packages("dplyr")
#install.packages("lmtest")
#install.packages("RCurl")
#install.packages("hdm")
#install.packages("glmnet")
#install.packages("randomcoloR")
library(httr)
library(jsonlite)
library(dplyr)
library(lmtest)
library(RCurl)
library(randomcoloR)
library(hdm)
library(glmnet)
options(stringsAsFactors = F)
url_robust <- "https://raw.githubusercontent.com/IsidoreBeautrelet/economictheoryblog/master/robust_summary.R"
eval(parse(text = getURL(url_robust, ssl.verifypeer = FALSE)),
     envir=.GlobalEnv)
```

## 1.2. Web crawling
```{r message=FALSE, cache=FALSE}
# url1 = "https://rent.591.com.tw/home/search/rsList?is_new_list=1&type=1&kind=0&searchtype=1&region=3"
# res = fromJSON(content(GET(url1),"text"))
# df = res$data$data
# 
# for(i in 1:60){
#   url2 = paste("https://rent.591.com.tw/home/search/rsList?is_new_list=1&type=1&kind=0&searchtype=1&region=1&firstRow=",i*30)
#   res = fromJSON(content(GET(url2),"text"))
#   df1 = res$data$data
#   df = rbind(df,df1)
# }
# 
# df = df[!duplicated(df),]
```

## 1.3. Data manipulation
```{r}
# df.1 = dplyr::select(df,price,area,floor,allfloor,browsenum_all,photoNum,fulladdress,shape,kind_name,section_name)
# a = as.character(regmatches(df.1$fulladdress,gregexpr("女",df.1$fulladdress)))
# a[a=="character(0)"] = 0
# a[a=="女"] = 1
# df.1$fulladdress = a
# df.1 = df.1[nchar(df.1$fulladdress)<3,]
# df.1$price = gsub("," , "",df.1$price)
# 
# for(i in 1:7){
#   df.1[,i] = as.numeric(df.1[,i])
# }
# df.1$shape = as.character(df.1$shape)
# df.1 = filter(df.1, shape!="7" &
#                 shape!="8" &
#                 kind_name!="其他" &
#                 kind_name!="車位" &
#                 allfloor<80 &
#                 floor<80 &
#                 area <500 & 
#                 price<700000)
# df.1$logprice = log(df.1$price)
load("part591.Rda")
```

# 2. Linear regression

## 2.1. Model 1 (price = a + b * area)
```{r}
#OLS
reg <- lm(data = df.1, price~area)
summary(reg)

#Test heteroskedasticity
bptest(data = df.1, price~area)

#Robust
reg1 <- lm(data = df.1, price~area)
summary(reg, robust = T)
coef1 <- coef(reg1)
coef1

yhat1 <- fitted(reg1)

plot(df.1$area,
     df.1$price,
     xlim = c(0,50),
     ylim = c(0,100000),
     xlab = "area",
     ylab = "price",
     cex = 0.3)+
abline(coef(reg1),col = "red",lwd = 2)+
abline(h = 0,v = 0, col = "black")
```

## 2.2. Model 2 (price = a + b1 * area + section dummies)
被省略的Dummy為士林區。
藍色是大安區。

```{r}
reg3 <- lm(data = df.1, price~area + factor(section_name))
summary(reg3,robust = T)

plot(df.1$area,
     df.1$price,
     xlim = c(0,50),
     ylim = c(0,100000),
     xlab = "area",
     ylab = "price",
     cex = 0.3) +
  abline(a = coef(reg3)[1],
         b = coef(reg3)[2],
         col = "red",
         lwd = 2) +
  abline(a = (coef(reg3)[1]+coef(reg3)[4]),
         b = coef(reg3)[2], 
         col = "blue",
         lwd = 2) +
  abline(h = 0, v = 0, col = "black")
```

## 2.3. Model 3 (price = a + b1 * area + section dummies + interaction)

藍色是文山區。

```{r}
reg4 <- lm(data = df.1, price ~ area + factor(section_name) + area:factor(section_name))
summary(reg4,robust = T)

plot(df.1$area,
     df.1$price,
     xlim = c(0,50),
     ylim = c(0,100000),
     xlab = "area",
     ylab = "price",
     cex = 0.3) +
  abline(a = coef(reg4)[1],
         b = coef(reg4)[2],
         col = "red",
         lwd = 2) +
  abline(a = (coef(reg4)[1]+coef(reg4)[8]),
         b = (coef(reg4)[2]+coef(reg4)[19]),
         col = "blue",
         lwd = 2) +
  abline(h = 0, v = 0, col = "black")
```

# 3. LASSO

## 3.1. Beta shrinkage
```{r}
kind <- model.matrix(~df.1$kind_name)
shape <- model.matrix(~df.1$shape)
section <- model.matrix(~df.1$section_name)
x <- as.matrix(cbind(df.1[,2:7],kind[,-1],shape[,-1],section[,-1]))
y <- df.1[,1]

lambda <- 10^seq(4, -4, length = 100)
lassoreg <- glmnet(x, y, alpha = 1, lambda = lambda)
betadf <- as.data.frame(as.matrix(lassoreg$beta))
colnames(betadf) <- lambda
betadf <- betadf[,seq(length(betadf)[1],1)]

plot(x = seq(-4, 4,length = 100),
     y = betadf[1,],
     type = "l",
     ylim = c(-4000,9000),
     ylab = "beta",
     xlab = "log(lambda)",
     col = "blue")+
  for(i in 2:25){
  lines(x = seq(-4, 4, length = 100), y = betadf[i,], type = "l",col = randomColor(24, hue ="blue"))
  }
```

## 3.2. Mean Square Error
```{r}
mse <- data.frame(matrix(ncol = length(betadf), nrow = length(y)))
for(i in 1:length(betadf)){
  for(j in 1:length(y)){
    mse[j,i] = (y[j] - t(x[j,]) %*% betadf[,i])^2 + sum(abs(betadf[,i]))
  }
}

plot(x = seq(-4, 4, length = 100)[1:90],
     y = colMeans(mse[1:90]),
     type = "l",
     col = "blue",
     xlab = "log(lambda)",
     ylab = "Mean Square Error")
```

## 3.3. Result{.tabset}

shape : 1.公寓 2.電梯大樓 3.透天厝 4.別墅 5.華廈 6.住宅大樓
被省略的Dummy為公寓

kind_name被省略的是分租套房。

###OLS
```{r}
regall <- lm(y ~ x)
summary(regall, robust = T)
```

###Lasso
```{r}
lasso <- rlasso(y ~ x ,post = FALSE)
summary(lasso,post = FALSE)
log10(lasso$lambda0)
```

